pipeline:
  build:
    image: golang:latest
    commands:
      - make test

  notify:
    image: plugins/webhook
    urls: https://msgbus.mills.io/ci.mills.io
    when:
      status: [ success, changed, failure ]
